node {
    properties(
        [
            pipelineTriggers([cron('H H/3 * * *')]),
            [$class: 'BuildDiscarderProperty', strategy: [$class: 'LogRotator', artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '10']]
        ]
    )
    sh """
    docker run --rm \
        --privileged \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v /etc:/etc:ro \
        -e REMOVE_VOLUMES=1 \
        spotify/docker-gc
    """
}