version: "2.1"
services:
  api:
    container_name: test-api
    restart: unless-stopped
    build:
      context: server
      dockerfile: Dockerfile
    depends_on: 
      - mongo
    entrypoint: /app/wait-for.sh
    command:
      - mongo:27017
      - --
      - npm
      - test
    volumes:
      - ./results:/app/results
    env_file: env/${ENVIRONMENT:-dev}

  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - mongotestdata:/data/db
    env_file: env/${ENVIRONMENT:-dev}

volumes:
  mongotestdata: