version: "2.1"
services:
  front:
    container_name: web
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on: 
      - api
    ports:
      - 80:80
    entrypoint: /wait-for.sh
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    command:
      - api:3000
      - --
      - nginx
      - -g
      - daemon off;

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: server
      dockerfile: Dockerfile
    depends_on: 
      - mongo
    entrypoint: /app/wait-for.sh
    command:
      - mongo:27017
      - --
      - npm
      - start
    # ports:
    #   - 3000:3000
    env_file: ./env/${ENVIRONMENT:-dev}

  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodata:/data/db
    env_file: ./env/${ENVIRONMENT:-dev}

volumes:
  mongodata: